<?php

$lang = array(

	'other' => 'Khác',
	'app_connent_ok' => 'Kết nối thành công ',
	'app_connent_false' => 'Kết nối thất bại',

	'note_deleteuser' => 'Xóa người dùng',
	'note_renameuser' => 'Đổi tên người dùng',
	'note_deletefriend' => 'Xóa bạn',
	'note_gettag' => 'Nhận TAG',
	'note_getcreditsettings' => 'Nhận cài đặt điểm ứng dụng',
	'note_updatecreditsettings' => 'Cập nhật cài đặt điểm ứng dụng',
	'note_updateclient' => 'Cập nhật bộ đệm ứng dụng',
	'note_updatepw' => 'Cập nhật mật khẩu người dùng',
	'note_updatebadwords' => 'Cập nhật danh sách bộ lọc từ',
	'note_updatehosts' => 'Cập nhật danh sách phân tích tên miền',
	'note_updateapps' => 'Cập nhật danh sách ứng dụng',
	'note_updatetagtemplate' => 'Cập nhật cài đặt mẫu thẻ',
	'note_list' => 'Danh sách thông báo',
	'note_test' => 'Kiểm tra',
	'note_delete' => 'Xóa',
	'note_succeed' => 'Thông báo thành công ',
	'note_na' => 'Không thông báo',
	'note_false' => 'Thông báo thất bại',
	'note_times' => 'lần',

	'pm_from' => 'Từ',
	'pm_to' => 'Đến',
	'pm_system' => 'Thông tin hệ thống',
	'pm_date' => 'Thời gian',
	'pm_daterange_1' => 'Hôm nay',
	'pm_daterange_2' => 'Hôm qua',
	'pm_daterange_3' => 'Hôm kia',
	'pm_daterange_4' => 'Tuần trước',
	'pm_daterange_5' => 'Sớm hơn',
	'pm_notitle' => '[không có tiêu đề]',

	'user_add' => 'Thêm người dùng',
	'user_delete' => 'Xóa người dùng',
	'login' => 'Đăng nhập',
	'logout' => 'Đăng xuất',
	'app_add' => 'Thêm ứng dụng mới',
	'app_delete' => 'Xóa ứng dụng',
	'app_edit' => 'Chỉnh sửa ứng dụng',
	'setting_update' => 'Cập nhật cài đặt cơ bản',
	'setting_register_update' => 'Cập nhật cài đặt đăng ký',
	'pm_send' => 'Gửi tin nhắn công khai',
	'pm_delete' => 'Xóa tin nhắn công khai',
	'pm_clear' => 'Xóa tin nhắn SMS',
	'badword_add' => 'Thêm bộ lọc từ',
	'badword_delete' => 'Xóa bộ lọc từ',
	'admin_add' => 'Thêm quản trị viên',
	'admin_pw_edit' => 'Sửa đổi mật khẩu người sáng lập',
	'admin_priv_edit' => 'Sửa đổi quyền của quản trị viên',
	'domain_add' => 'Thêm độ phân giải tên miền',
	'domain_delete' => 'Xóa phân giải tên miền',
	'credit_addexchange' => 'Cập nhật chương trình đổi điểm',
	'credit_deleteexchange' => 'Xóa chương trình đổi điểm',
	'credit_sync' => 'Đồng bộ hóa cài đặt tín dụng được áp dụng',
	'db_export' => 'Sao lưu dữ liệu',
	'db_import' => 'Phục hồi dữ liệu',
	'db_delete' => 'Xóa dữ liệu',
	'note_delete' => 'Xóa thông báo',
	'note_send' => 'Thông báo phát hành lại',
	'dumpfile_exists' => 'Sao lưu tồn tại',
	'dumpfile_not_exists' => 'Dự phòng không tồn tại',
);